# Generated by Django 2.0 on 2017-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0002_auto_20171225_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=20480),
        ),
    ]
