# Generated by Django 2.0 on 2017-12-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0003_auto_20171225_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
