# Generated by Django 2.0 on 2017-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0005_auto_20171226_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-time_created',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-time_created',)},
        ),
        migrations.AddField(
            model_name='log',
            name='accessed_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
